#!/usr/bin/env python3
"""
Master script: generate all Supplementary Figures S2–S7.

Usage:
    python scripts/si_figures/make_all_si_figures.py

Prerequisites:
    - revision_results/ populated by prior export scripts
    - identity robustness data generated by generate_identity_robustness_data.py

Output directory: revision_results/si_figures/
Each figure produces: .pdf, .svg, .png, _notes.txt
"""
import subprocess, sys, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts" / "si_figures"

# Step 0: generate derived data if missing
robustness_dir = ROOT / "revision_results" / "identity_robustness"
if not (robustness_dir / "perturbation_sweep.csv").exists():
    print("Generating identity robustness data …")
    subprocess.check_call([sys.executable,
                           str(SCRIPTS / "generate_identity_robustness_data.py")])

# Step 1–6: plot each figure
scripts = [
    "plot_fig_s2.py",
    "plot_fig_s3.py",
    "plot_fig_s4.py",
    "plot_fig_s5.py",
    "plot_fig_s6.py",
    "plot_fig_s7.py",
]

t0 = time.time()
for s in scripts:
    print(f"\n{'='*60}")
    print(f"Running {s} …")
    print(f"{'='*60}")
    subprocess.check_call([sys.executable, str(SCRIPTS / s)])

elapsed = time.time() - t0
print(f"\n{'='*60}")
print(f"All SI figures generated in {elapsed:.1f} s")
print(f"Output: {ROOT / 'revision_results' / 'si_figures'}")

# Verify all outputs
outdir = ROOT / "revision_results" / "si_figures"
expected = []
for i in range(2, 8):
    for ext in ("pdf", "svg", "png"):
        expected.append(f"Fig_S{i}.{ext}")
    expected.append(f"Fig_S{i}_notes.txt")

missing = [f for f in expected if not (outdir / f).exists()]
if missing:
    print(f"\n⚠ Missing files: {missing}")
else:
    print(f"\n✓ All {len(expected)} files present")
    for f in sorted(outdir.iterdir()):
        sz = f.stat().st_size
        print(f"  {f.name:25s}  {sz:>8,} bytes")
